#!/bin/sh

set -e
set -u
set -x

aws s3 sync . s3://pkg.develboard.com/ --region eu-west-1 \
    --delete \
    --exclude "$(basename ${0})" \
    --exclude "x86_64-nativesdk" \
    --exclude "Packages"
