#!/bin/sh
#
# Author: Lorenzo Villani <lvillani@develer.com>
#
# Licensed as Public Domain
#


has_inst() {
    ar p ${1} 'control.tar.gz' | tar tvz | grep -E '(prerm|postinst)'
}

find -iname '*.ipk' | while read line; do
    ret="$(has_inst ${line})"
    if [ -n "${ret}" ]; then
        echo "${line}"
    fi
done
