#!/bin/sh

set -e
set -u

BASEURL="https://toolchain.develboard.com"

ls develboard-glibc-x86_64*-toolchain*.sh 1>/dev/null 2>&1 || {
    echo "Cannot find toolchain installer files. Aborting"
    exit 1
}

ls develboard-glibc-x86_64*-toolchain*.manifest 1>/dev/null 2>&1 || {
    echo "Cannot find toolchain manifest files. Aborting"
    exit 1
}

# Generate an HTML page with a list of SDKs and links to download them
#
# WARNING: The list will be overwritten with whatever is in the current directory
# when you launch the script.

cat >index.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>DevelBoard Toolchain</title>
</head>
<body>
    <h1>DevelBoard Blue Toolchain</h1>
    <ul>
EOF

for f in *.sh; do
    bf=$(basename "${f}")
    sha1=$(sha1sum "${f}" | cut -d' ' -f1)
    size=$(ls -lSh "${f}" | awk '{print $5}')

    case "${bf}" in
    *core-image-develboard-full*)
        desc="Full C/C++ toolchain for DevelBoard Blue, including all support headers and libraries for third-party packages"
        ;;
    *)
        desc="Basic C/C++ toolchain for DevelBoard Blue"
        ;;
    esac

    echo "        <li><a href=\"${BASEURL}/${bf}\">${bf}</a><br>${desc}<br>Size: ${size}<br>SHA1: <code>${sha1}</code></li>" >>index.html
done

cat >>index.html <<EOF
    </ul>
</body>
</html>
EOF

aws --profile develboard-toolchain --region eu-west-1 \
    s3 sync ./ s3://toolchain.develboard.com/

for f in *.sh; do
    bf=$(basename "${f}")

    aws --profile develboard-toolchain --region eu-west-1 \
        s3api copy-object --bucket toolchain.develboard.com --content-type "application/octet-stream" \
        --copy-source "toolchain.develboard.com/${bf}" --key "${bf}" --metadata-directive "REPLACE"
done
